spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qwe123!@#
  servlet:
    multipart:
      max-file-size: 20MB      # 单个文件最大 20MB
      max-request-size: 100MB  # 总上传数据最大 100MB
file:
  upload-dir: ./upload/files/   # 项目根目录下的文件夹


